[package]
name = "publish"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
cargo_metadata = "0.14.0"
cradle = { path = "../../../../cradle" }
structopt = "0.3.22"
tempfile = "3.2.0"
