version: '3'
services:

  bitcoin-core:
    image: ruimarinho/bitcoin-core:0.21.1
    container_name: bitcoin-core
    volumes:
      - ~/.bitcoin:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
      - 18332:18332
      - 28334:28334

  lnd:
    image: lnd
    container_name: lnd
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - NETWORK=testnet
      - RPCHOST=bitcoin-core
      - BACKEND=bitcoind
      - TARGETHOST=lnd
    depends_on:
      - "tor-node"
    volumes:
      - lnd_dir:/root/.lnd
      - tor-dir:/var/lib/tor
    links:
      - "bitcoin-core:bitcoin-core"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["./start-lnd.sh"]

  tor-node:
    image: osminogin/tor-simple
    container_name: tor-node
    restart: always
    expose:
      - "9051"
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - tor-dir:/var/lib/tor

  agora:
    image: agora
    container_name: agora
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - "lnd"
    environment:
      - LND_RPC_AUTHORITY=lnd:10009
      - AGORA_PORT=1234
      - FILES_DIR=/root/agora-files
      - TLS_CERT_PATH=/root/.lnd/tls.cert
      - INVOICES_MACAROON_PATH=/root/.lnd/data/chain/bitcoin/testnet/invoice.macaroon
    volumes:
      - lnd_dir:/root/.lnd
      - agora_files_dir:/root/agora-files
    ports:
      - 1234:1234
      - 1235:1235
    links:
      - "bitcoin-core:bitcoin-core"
      - "lnd:lnd"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["./entrypoint.sh"]

volumes:
  lnd_dir:
    driver: local
  tor-dir:
    driver: local
  agora_files_dir:
    driver: local
