[package]
name = "layer-playground"
version = "0.1.0"
authors = ["Sönke Hahn <soenkehahn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.15"
http = "0.2.4"
tower = "0.4.8"
