name: Audit
on:
  pull_request:
    branches:
    - master
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
